name = "RandomParamApprox"
uuid = "ecc3a655-e20b-4a68-9b7b-c991812baa6a"
authors = ["Alexander Browning"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
